'use client'
import Link from 'next/link'
import { FormEvent, useEffect, useState } from 'react'
import { demoLoadouts } from '@/lib/demo-data'
import { Loadout, Mode } from '@/lib/types'
import { createClient, isSupabaseConfigured } from '@/lib/supabase'
const blank={name:'',mode:'battle-royale' as Mode,category:"Fusil d’assaut",role:'Longue portée',tier:'S' as const,score:90,code:'',description:'',tags:'',attachments:''}
export default function Admin(){const [items,setItems]=useState<Loadout[]>([]);const [form,setForm]=useState(blank);const [msg,setMsg]=useState('')
useEffect(()=>{(async()=>{if(!isSupabaseConfigured){setItems(demoLoadouts);return}const {data}=await createClient()!.from('loadouts').select('*').order('score',{ascending:false});setItems(data||[])})()},[])
async function add(e:FormEvent){e.preventDefault();const payload={...form,slug:form.name.toLowerCase().replace(/[^a-z0-9]+/g,'-'),tags:form.tags.split(',').map(x=>x.trim()).filter(Boolean),attachments:form.attachments.split('\n').map(x=>{const [slot,name]=x.split(':');return{slot:slot?.trim(),name:name?.trim()}}).filter(x=>x.slot&&x.name),published:true};if(!isSupabaseConfigured){setMsg('Ajout simulé en mode démo. Connecte Supabase pour enregistrer.');return}const {error}=await createClient()!.from('loadouts').insert(payload);setMsg(error?error.message:'Classe ajoutée.');if(!error)location.reload()}
async function remove(id:string){if(!isSupabaseConfigured){setMsg('Suppression simulée en mode démo.');return}await createClient()!.from('loadouts').delete().eq('id',id);setItems(items.filter(x=>x.id!==id))}
return <main className="admin-page"><header><div><Link href="/">← Site public</Link><h1>Administration</h1><p>Gère les classes sans modifier le code.</p></div><span className="env-badge">{isSupabaseConfigured?'Supabase connecté':'Mode démo'}</span></header><div className="admin-grid"><form className="admin-form" onSubmit={add}><h2>Ajouter une classe</h2><input placeholder="Nom de l’arme" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><div className="form-row"><select value={form.mode} onChange={e=>setForm({...form,mode:e.target.value as Mode})}><option value="battle-royale">Battle Royale</option><option value="resurgence">Résurgence</option><option value="ranked">Ranked</option><option value="multiplayer">Multijoueur</option><option value="zombies">Zombies</option></select><select value={form.tier} onChange={e=>setForm({...form,tier:e.target.value as any})}><option>S+</option><option>S</option><option>A</option><option>B</option></select></div><input placeholder="Catégorie" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><input placeholder="Rôle" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}/><input type="number" min="0" max="100" value={form.score} onChange={e=>setForm({...form,score:Number(e.target.value)})}/><input placeholder="Code de classe" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/><textarea placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input placeholder="Tags séparés par des virgules" value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})}/><textarea placeholder={'Accessoires, une ligne par accessoire\nOptique: FANG ELO\nCanon: Heavy Barrel'} value={form.attachments} onChange={e=>setForm({...form,attachments:e.target.value})}/><button>Ajouter la classe</button>{msg&&<div className="notice">{msg}</div>}</form><section className="admin-list"><h2>Classes existantes</h2>{items.map(x=><article key={x.id}><div><strong>{x.name}</strong><span>{x.mode} · Tier {x.tier} · {x.score}/100</span></div><button onClick={()=>remove(x.id)}>Supprimer</button></article>)}</section></div></main>}
