import { Loadout } from './types'
export const demoLoadouts: Loadout[] = [
  {id:'1',name:'MXR-17',slug:'mxr-17-br',mode:'battle-royale',category:"Fusil d’assaut",role:'Longue portée',tier:'S+',score:96,code:'A03-36W2S-J343H-11',description:'Une classe stable et polyvalente pour contrôler les combats à moyenne et longue portée.',tags:['Faible recul','Polyvalent','Longue portée'],attachments:[{slot:'Optique',name:'FANG HoverPoint ELO'},{slot:'Bouche',name:'Silencieux monolithique'},{slot:'Canon',name:'Greaves Scourge 17 pouces'},{slot:'Chargeur',name:'Rhodes Drum Mag'},{slot:'Crosse',name:'Winch Stock'}],published:true,updated_at:'2026-07-14T00:00:00Z'},
  {id:'2',name:'Carbon 57',slug:'carbon-57-resurgence',mode:'resurgence',category:'Mitraillette',role:'Corps à corps',tier:'S+',score:98,code:'S05-9CWYE-H511',description:'Une configuration très mobile conçue pour enchaîner les combats rapprochés.',tags:['Mobilité','Rush','TTK rapide'],attachments:[{slot:'Bouche',name:'LTI Stentorian Brake'},{slot:'Canon',name:'Orbital Light 8,6 pouces'},{slot:'Crosse',name:'Hammer Platoon Pad'},{slot:'Accessoire',name:'VAS Convergence Foregrip'},{slot:'Chargeur',name:'MFS Renown Plus Mag'}],published:true,updated_at:'2026-07-14T00:00:00Z'},
  {id:'3',name:'AK-27',slug:'ak-27-ranked',mode:'ranked',category:"Fusil d’assaut",role:'Ancrage',tier:'S',score:91,code:'A02-2G9PV-4C1XB-11',description:'Une arme puissante pour tenir une position et punir les rotations adverses.',tags:['Compétitif','Dégâts','Précision'],attachments:[{slot:'Optique',name:'FANG HoverPoint ELO'},{slot:'Bouche',name:'Silencieux monolithique'},{slot:'Canon',name:'Vandal Heavy 17,6 pouces'},{slot:'Chargeur',name:'Saber Heavy Drum'},{slot:'Crosse',name:'Pugil Heavy Stock'}],published:true,updated_at:'2026-07-14T00:00:00Z'},
  {id:'4',name:'Viper X9',slug:'viper-x9-multi',mode:'multiplayer',category:'Mitraillette',role:'Rush',tier:'S',score:90,code:'MP9-VPR-3301',description:'Une classe nerveuse pour les modes à objectif et les prises de flanc.',tags:['Flank','Rapide','Objectif'],attachments:[{slot:'Bouche',name:'Flash Hider'},{slot:'Canon',name:'CQB Short'},{slot:'Laser',name:'Tactical Laser'},{slot:'Chargeur',name:'Fast Mag'},{slot:'Crosse',name:'Raider Pad'}],published:true,updated_at:'2026-07-14T00:00:00Z'},
  {id:'5',name:'Titan LMG',slug:'titan-lmg-zombies',mode:'zombies',category:'Mitrailleuse',role:'DPS',tier:'S+',score:98,code:'Z-TTN-9001',description:'Un grand chargeur et des dégâts constants pour les manches élevées.',tags:['DPS','Boss','Manches élevées'],attachments:[{slot:'Optique',name:'Reflex Clean'},{slot:'Canon',name:'Heavy Duty'},{slot:'Chargeur',name:'Extended Box III'},{slot:'Poignée',name:'Sustained Grip'},{slot:'Munition',name:'Armor Piercing'}],published:true,updated_at:'2026-07-14T00:00:00Z'},
  {id:'6',name:'Strider 300',slug:'strider-300-br',mode:'battle-royale',category:'Fusil de précision',role:'Sniper',tier:'S',score:90,code:'R07-2JD6P-5NM5G-6J11',description:'Un sniper conçu pour ouvrir les combats sur les grandes cartes.',tags:['One-shot','Précision','Grande portée'],attachments:[{slot:'Bouche',name:'Silencieux monolithique'},{slot:'Canon',name:'Bowen 25 pouces'},{slot:'Chargeur',name:'Carnation Fast Mag'},{slot:'Poignée',name:'Hatch Quick Grip'},{slot:'Munition',name:'.300 WM Overpressured'}],published:true,updated_at:'2026-07-14T00:00:00Z'}
]
